# Generated by Django 5.1.13 on 2025-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
